name: Create Release Branch and PR

# This workflow runs automatically every Saturday at 12:00 PM IST (06:30 UTC)
# and can also be run manually with an optional version input.
on:
  schedule:
    - cron: "30 6 * * 6" # 06:30 UTC on Saturday (12:00 PM IST)
  workflow_dispatch:
    inputs:
      version:
        description: "The semantic version to use (e.g., 1.2.3)"
        required: false

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout develop branch
        uses: actions/checkout@v4
        with:
          ref: develop

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm ci

      - name: Run linter
        run: npm run lint

  create-pr:
    needs: lint # Run only if 'lint' succeeds
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout develop branch (full history for tags)
        uses: actions/checkout@v4
        with:
          ref: develop
          fetch-depth: 0 # crucial to fetch all history and tags

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm ci

      - name: Compute version (no write)
        id: compute_version
        shell: bash
        run: |
          set -euo pipefail

          CURR=$(node -p "require('./package.json').version")
          INPUT="${{ github.event.inputs.version || '' }}"
          EVENT="${{ github.event_name }}"

          bump_semver () {
            local ver="$1" kind="$2"
            ver_base="${ver%%-*}"
            IFS='.' read -r a b c <<< "$ver_base"
            a=${a:-0}; b=${b:-0}; c=${c:-0}
            case "$kind" in
              major) a=$((a+1)); b=0; c=0 ;;
              minor) b=$((b+1)); c=0 ;;
              patch|*) c=$((c+1)) ;;
            esac
            printf "%d.%d.%d" "$a" "$b" "$c"
          }

          if [ "$EVENT" = "schedule" ]; then
            NEW=$(bump_semver "$CURR" "patch")
          elif [ -n "$INPUT" ]; then
            if [[ "$INPUT" =~ ^(major|minor|patch)$ ]]; then
              NEW=$(bump_semver "$CURR" "$INPUT")
            elif [[ "$INPUT" =~ ^[0-9]+(\.[0-9]+){2}(-[0-9A-Za-z.-]+)?$ ]]; then
              NEW="$INPUT"
            else
              echo "Invalid version input: $INPUT" >&2; exit 1
            fi
          else
            echo "No version specified for manual trigger." >&2; exit 1
          fi

          echo "new_version=$NEW" >> "$GITHUB_OUTPUT"

      - name: Check if there are changes to release
        id: check_changes
        run: |
          set -euo pipefail
          git fetch origin master
          
          # Check if develop has commits ahead of master
          AHEAD_COUNT=$(git rev-list --count origin/master..HEAD)
          echo "Commits ahead of master: $AHEAD_COUNT"
          
          if [ "$AHEAD_COUNT" -eq 0 ]; then
            echo "No new commits to release. Develop is up to date with master."
            echo "has_changes=false" >> "$GITHUB_OUTPUT"
            exit 0
          else
            echo "Found $AHEAD_COUNT commits to release."
            echo "has_changes=true" >> "$GITHUB_OUTPUT"
          fi

      - name: Generate release notes
        id: release_notes
        if: steps.check_changes.outputs.has_changes == 'true'
        shell: bash
        run: |
          # Find the last tag on the master branch
          LAST_TAG=$(git describe --tags --abbrev=0 origin/master 2>/dev/null || echo "")

          if [ -z "$LAST_TAG" ]; then
            echo "No previous tag found. Generating release notes from all commits on develop."
            LOG_RANGE="origin/master..HEAD"
          else
            echo "Found last tag: $LAST_TAG. Generating notes from new commits."
            LOG_RANGE="$LAST_TAG..HEAD"
          fi

          # Bulleted list of commit messages (oldest first)
          RELEASE_NOTES=$(git log --pretty=format:'- %s' --reverse $LOG_RANGE)

          # Escape for GitHub Actions output
          RELEASE_NOTES="${RELEASE_NOTES//'%'/'%25'}"
          RELEASE_NOTES="${RELEASE_NOTES//$'\n'/'%0A'}"
          RELEASE_NOTES="${RELEASE_NOTES//$'\r'/'%0D'}"

          echo "release_notes=$RELEASE_NOTES" >> "$GITHUB_OUTPUT"

      - name: Create release branch and bump version
        if: steps.check_changes.outputs.has_changes == 'true'
        shell: bash
        run: |
          set -euo pipefail
          
          RELEASE_BRANCH="release/v${{ steps.compute_version.outputs.new_version }}"
          NEW_VERSION="${{ steps.compute_version.outputs.new_version }}"
          
          # Create and checkout new release branch from current develop
          git checkout -b "$RELEASE_BRANCH"
          
          # Bump version in package.json
          npm version "$NEW_VERSION" --no-git-tag-version
          
          # Configure git for commits
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          
          # Stage version changes
          git add package.json package-lock.json
          
          # Commit version bump
          git commit -m "chore(release): bump version to v$NEW_VERSION"
          
          # Push the release branch
          git push origin "$RELEASE_BRANCH"

      - name: Create Pull Request
        if: steps.check_changes.outputs.has_changes == 'true'
        id: release_pr
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          title: "Release v${{ steps.compute_version.outputs.new_version }}"
          commit-message: "chore(release): prepare release v${{ steps.compute_version.outputs.new_version }}"
          body: |
            ## Release v${{ steps.compute_version.outputs.new_version }}
            
            This release includes the following changes:
            
            ### Changes
            ${{ steps.release_notes.outputs.release_notes }}
            
            ### Version Bump
            - Updated version from current to v${{ steps.compute_version.outputs.new_version }}
            
            ---
            *This PR was created automatically by the release workflow.*
          branch: "release/v${{ steps.compute_version.outputs.new_version }}"
          base: master
          labels: "release,automated"
          # Don't specify add-paths to include ALL changes from develop

      - name: Output results
        if: steps.check_changes.outputs.has_changes == 'true'
        run: |
          if [ "${{ steps.release_pr.outputs.pull-request-number }}" != "" ]; then
            echo "✅ Pull Request created successfully!"
            echo "📋 PR Number: ${{ steps.release_pr.outputs.pull-request-number }}"
            echo "🔗 PR URL: ${{ steps.release_pr.outputs.pull-request-url }}"
            echo "🌿 Branch: ${{ steps.release_pr.outputs.pull-request-branch }}"
            echo "📦 Version: v${{ steps.compute_version.outputs.new_version }}"
          else
            echo "❌ Failed to create pull request"
            exit 1
          fi

      - name: No changes to release
        if: steps.check_changes.outputs.has_changes == 'false'
        run: |
          echo "ℹ️  No new changes to release. Develop branch is up to date with master."
