name: Post PR Checks

on:
  pull_request:
    branches:
      - develop
      - master
      - 'release/**'
    types: [opened, synchronize, reopened]

permissions:
  pull-requests: write
  issues: write

jobs:
  notify-and-comment:
    runs-on: ubuntu-latest

    steps:
      # Optional: Show PR info in logs
      - name: Show PR details
        run: |
          echo "Pull Request Number: ${{ github.event.pull_request.number }}"
          echo "Title: ${{ github.event.pull_request.title }}"
          echo "Author: ${{ github.event.pull_request.user.login }}"

      # Add a comment to the PR
      - name: Add PR comment
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body: "🚨 Heads up! Please update the pull request in the *Eximso Developer* WhatsApp group 📱. \n\nAlso, remember: *With great PRs comes great responsibility!* 🕷️"
            })

      # Cool extra — add a PR label
      - name: Add 'needs-whatsapp-update' label
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            await github.rest.issues.addLabels({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              labels: ['needs-whatsapp-update']
            })
